# helm-applications/simple-test-chart.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-test-chart
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cgn170/argocd-test
    path: helm/simple-test-chart
    targetRevision: main
    helm:
      values: |
        replicaCount: 2
        image:
          repository: nginx
          tag: "1.21"
        service:
          type: ClusterIP
          port: 80
  destination:
    server: https://kubernetes.default.svc
    namespace: simple-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
